
YAHOO.namespace('news');if(!YD)var YD=YAHOO.util.Dom;if(!YE)var YE=YAHOO.util.Event;if(!$)var $=YD.get;var subURL='http://webservices.sitebuilder.customerstreet.com/rapidsite/xstandard/';var clientID;document.createParamElement=function(type,name,value){var element;try{element=document.createElement('<'+type+' name="'+name+'" value="'+value+'">');}catch(e){}
if(!element||!element.name){element=document.createElement(type)
element.name=name;element.value=value;}
return element;}
YAHOO.news.xsEdit={xsDialog:null,submitUrl:"/plugins/news/extras/news_ajax.php",imageHeight:null,imageWidth:null,self:this,setup:function(o){if(document.getElementById('admin_toolbar')){$('news_plugin').style.display='none';var clientEdit=YD.getElementsByClassName('client_edit','div','content_inner_wrapper');YE.addListener(clientEdit,'click',this.editElement);var clientEdit=YD.getElementsByClassName('client_edit','h2','content_inner_wrapper');YE.addListener(clientEdit,'click',this.editElement);this.addTooltips(clientEdit);var xStandard=YD.getElementsByClassName('news_plugin','form','extra_2')[0];YE.on(xStandard,'submit',this.catchXSSubmit);}},catchXSSubmit:function(e){var pageCopy=document.getElementById('page_copy');pageCopy.EscapeUnicode=true;document.getElementById('xhtml').value=pageCopy.value;},getNodeName:function(tag){tag=tag.toLowerCase();switch(tag){case'h2':var tagName='Main Heading';break;case'h3':var tagName='Sub-Heading';break;case'h4':var tagName='Minor Heading';break;case'p':var tagName='Paragraph';break;case'li':case'ul':case'ol':var tagName='List';break;case'img':var tagName='Image';break;default:var tagName=false;}
return tagName;},getEditNode:function(queryNode){while(queryNode.nodeType!=3&&queryNode.nodeName.toLowerCase()!='img'){queryNode=queryNode.hasChildNodes?queryNode.firstChild:queryNode.nextSibling;}
if(queryNode.parentNode.nodeName.toLowerCase()=='strong'||queryNode.parentNode.nodeName.toLowerCase()=='em'||queryNode.nodeType==3){queryNode=queryNode.parentNode;}
return queryNode;},addTooltips:function(elementList){if(elementList.length){var wrapper=document.getElementById("content_inner_wrapper");if(!YD.hasClass(wrapper,'yui-skin-sam'))YD.addClass(wrapper,'yui-skin-sam');var tagList=['h3','p','img','ul'];var idList=[];var thisNode;var contentType;for(var i=0;i<elementList.length;i++){if(!elementList[i].getElementsByTagName)continue;for(var n=0;n<tagList.length;n++){var nodes=elementList[i].getElementsByTagName(tagList[n]);for(var x=0;x<nodes.length;x++){var thisNode=nodes[x];if(!thisNode.hasAttribute('id')){thisNode.setAttribute('id','tooltip_node_'+x);}
contentType=YX.getNodeName(thisNode.nodeName);content='Edit this '+contentType+' by clicking on it.';thisNode.setAttribute('title',content);idList[idList.length]=thisNode.getAttribute('id');}}}
YX.toolTip=new YAHOO.widget.Tooltip("simple_tooltip",{context:idList,container:wrapper});}else{return false;}},closeDialog:function(){YX.xsDialog.destroy();YX.xsDialog=null;return true;},updateDom:function(elementId,domNode){var oldNode=document.getElementById(elementId);if(oldNode.hasChildNodes()){var oldChild=oldNode.firstChild;while(oldChild){var nextChild=oldChild.nextSibling;oldChild.parentNode.removeChild(oldChild);oldChild=nextChild;}}
if(domNode.hasChildNodes()){newChild=domNode.firstChild;while(newChild){var nextChild=newChild.nextSibling;oldNode.appendChild(newChild);newChild=nextChild;}}
return true;},getXmlFromString:function(xml_string){if(window.ActiveXObject){var xml_doc=new ActiveXObject('Microsoft.XMLDOM');xml_doc.async='false';xml_doc.loadXML(xml_string);}else{var xml_parser=new DOMParser();var xml_doc=xml_parser.parseFromString(xml_string,'text/xml');if(xml_doc.documentElement.nodeName=='parsererror'){return false;}}
var xml_root=xml_doc.documentElement;return xml_root;},getXmlFromDom:function(domNode){if(domNode.hasAttribute("style"))domNode.removeAttribute('style');var children=YD.getChildren(domNode);for(var i=0;i<children.length;i++){if(children[i].hasAttribute('style'))children[i].removeAttribute('style');}
if(domNode.xml){var xmlValue=domNode.xml;}else{var newDom=document.implementation.createDocument("http://www.w3.org/1999/xhtml","html",null);var newNode=newDom.importNode(domNode,true);newDom.documentElement.appendChild(newNode);var xmlSerialiser=new XMLSerializer();var xmlValue=xmlSerialiser.serializeToString(newDom.documentElement);}
return xmlValue;},createEditor:function(editNode,xsId,xsForm,dimxy,buttons,tagName){this.method;this.newParam=[];this.newParam.toolbar={'name':'ToolbarWysiwyg','value':buttons};this.newParam.styles={'name':'ShowStyles','value':'yes'};this.newParam.victim={'name':'Victim','value':editNode.id};this.newParam.timestamp={'name':'EnableTimestamp','value':'no'};var xsEditor=xsForm.cloneNode(true);var id=xsId;var width=dimxy[0];var height=dimxy[1];if(editNode.hasChildNodes()){var child=editNode.firstChild;while(child){if(child.nodeType!=3){var xmlValue=editNode.innerHTML;break;}
child=child.nextSibling;}}
if(typeof xmlValue=='undefined'){if(navigator.appVersion.indexOf("MSIE")!==-1){var xmlValue='<h2>'+$('header_1').innerHTML+'</h2>';}else{var xmlValue=YX.getXmlFromDom(editNode);}}
var self=this;var xsObject=xsEditor.getElementsByTagName('object')[0];var editor=document.createElement('div');var editHead=document.createElement('div');var editHeadText=document.createTextNode('Edit this '+tagName);var editBody=document.createElement('div');var setParameters=function(xs){if(navigator.appVersion.indexOf("MSIE")!==-1){var objParametersOut=document.getElementById('page_copy');var objParameters=objParametersOut.getElementsByTagName("param");}else{var objParameters=xs.getElementsByTagName("param");}
for(var i=0;i<objParameters.length;i++){var paramName=objParameters[i].getAttribute('name');var paramValue=objParameters[i].getAttribute('value');switch(paramName){case'width':objParameters[i].value=width;break;case'height':objParameters[i].value=height;break;case'Value':if(navigator.appVersion.indexOf("MSIE")!=-1){xmlValue=str_replace('"','&quot;',xmlValue);}
objParameters[i].value=xmlValue;break;case'ClientID':clientID=objParameters[i].value;break;default:continue;}}};var createParameters=function(xs){if(navigator.appVersion.indexOf("MSIE")!=-1){subURL=$('xstandardBase').value;paramNode=document.createParamElement('param','ClientID',clientID);xs.appendChild(paramNode);paramNode=document.createParamElement('param','License',subURL+'license.txt');xs.appendChild(paramNode);paramNode=document.createParamElement('param','Styles',subURL+'styles.xml');xs.appendChild(paramNode);paramNode=document.createParamElement('param','ImageLibraryURL',subURL+'image_library/imagelibrary.php '+subURL+'image_library/publiclibrary.php');xs.appendChild(paramNode);paramNode=document.createParamElement('param','Base',subURL+'document_library');xs.appendChild(paramNode);paramNode=document.createParamElement('param','AttachmentLibraryURL',subURL+'document_library/attachmentlibrary.php');xs.appendChild(paramNode);paramNode=document.createParamElement('param','SpellCheckerURL',subURL+'spellchecker/spellchecker.php');xs.appendChild(paramNode);paramNode=document.createParamElement('param','Options','66054');xs.appendChild(paramNode);paramNode=document.createParamElement('param','Value',xmlValue);xs.appendChild(paramNode);}
for(var param in self.newParam){paramNode=document.createParamElement('param',self.newParam[param].name,self.newParam[param].value);xs.appendChild(paramNode);}};if(xsObject){xsObject.setAttribute("id","xsedit");xsObject.setAttribute("width",width);xsObject.setAttribute("height",height);setParameters(xsObject);createParameters(xsObject);}
editor.setAttribute("id",xsId);editHead.setAttribute("class","hd");editHead.setAttribute("className","hd");editHead=editor.appendChild(editHead);editHead.appendChild(editHeadText);editBody.setAttribute("class","bd");editBody.setAttribute("className","bd");editBody=editor.appendChild(editBody);xsEditor.setAttribute("action",YX.submitUrl);xsEditor=editBody.appendChild(xsEditor);var keyWordHead=document.createElement('h3');keyWordHead.setAttribute('id','keyWordHead');editor.appendChild(keyWordHead);keyWordHead.appendChild(document.createTextNode('Your Page Key Phrases'));var keyWords=document.getElementById('keyphraseList');keyWords=keyWords.cloneNode(true);keyWords.id='keyphraseListClone';editor.appendChild(keyWords);keyWords.style.display='block';var containerSave=document.createElement('div');editor.appendChild(containerSave);containerSave.setAttribute('id','container-save');if(Dom.hasClass(editNode,'news_desc')){var newsId=Dom.getAncestorByTagName(editNode,'div');newsId=newsId.id;YE.on(containerSave,'click',changeDesc,newsId);}else{YE.on(containerSave,'click',saveButtonClicked);}
return editor;},getEditor:function(element,buttons,tagName){var editExists=YD.getElementsByClassName('yui-dialog','div','extra_2');if(editExists.length>0){if(YX.xsDialog!=null)YX.xsDialog.destroy();if(YX.imgDialog!=null)YX.imgDialog.destroy();}
editExists=null;width=600;height=400;if(tagName=='Image'){width=parseInt(YD.getStyle(element,'width'))+30;height=parseInt(YD.getStyle(element,'height'))+60;}
if(document.forms["news_plugin"]=='undefined'){return false;}
var xsForm=document.forms["news_plugin"];var xsEditor=YX.createEditor(element,'editor',xsForm,[width,height],buttons,tagName);var parent=document.getElementById('extra_2');parent.appendChild(xsEditor);YX.xsDialog=new YAHOO.widget.Dialog(xsEditor,{fixedcenter:true,modal:true,close:true,width:"620px",zIndex:1000});YX.xsDialog.render();YX.xsDialog.show();var editorMask=$('editor_mask');if(editorMask){maskHeight=editorMask.style.cssText;maskHeight=maskHeight.split('; ');newMaskHeight=new Array();var j=0;for(var i=0;i<maskHeight.length;i++){newMaskHeight[j]=maskHeight[i].split(': ');j++;}
for(var i=0;i<newMaskHeight.length;i++){theMaskHeight=newMaskHeight[i].toString();theMaskHeight=theMaskHeight.split(',');if(theMaskHeight[0].toLowerCase()=='height'){i++;var theRealMaskHeight=theMaskHeight[1];}}
maskHeight=theRealMaskHeight.split('px');maskHeight=maskHeight[0];maskHeight=parseFloat(maskHeight);maskHeight=maskHeight-520;editorMask.style.cssText='z-index: 1001; height: '+maskHeight+'px; width: 1263px; display: block;';}
return true;},getNewsEditor:function(element,buttons,tagName,formId){function submitDetails(e){YE.stopEvent(e);var extracontainer=$('newsextracontainer');var newsForm=extracontainer.getElementsByTagName('form')[0];var formData=YAHOO.util.Connect.setForm(newsForm);var siteId=document.getElementById("siteid_news_plugin").value;var pageId=document.getElementById("pageid_news_plugin").value;var newsSubmitUrl="/plugins/news/extras/news_ajax.php";var newsPostData='siteid='+siteId+'&pageid='+pageId+'&nodeid='+element.id+'&savedb=1';var newscopy=YAHOO.util.Connect.asyncRequest('POST',newsSubmitUrl,newsUpdateComplete,newsPostData);}
var extradetailsdiv=$('author_category_fields');var extradetails=extradetailsdiv.cloneNode(true);var newscontainerdiv=$('newsextracontainer');if(newscontainerdiv==null||newscontainerdiv=='undefined'){newscontainerdiv=document.createElement('div');newscontainerdiv.setAttribute('id','newsextracontainer');element.parentNode.appendChild(newscontainerdiv);}
YX.xsDialog=new YAHOO.widget.Dialog(newscontainerdiv,{fixedcenter:true,modal:true,close:true,width:"550px",zIndex:1000});YX.xsDialog.setHeader("Set the extra details for this article");YX.xsDialog.setBody(extradetails);YX.xsDialog.render();YX.xsDialog.show();var containerSave=document.createElement('div');newscontainerdiv.appendChild(containerSave);containerSave.setAttribute('id','container-save');YE.on(containerSave,'click',submitDetails);},saveContent:{copy:null,siteId:null,pageId:null,nodeId:null,submitUrl:null,update:function(){this.siteId=document.getElementById("siteid_news_plugin").value;this.pageId=document.getElementById("pageid_news_plugin").value;this.copy=escape(this.copy);if(this.copy==''){this.copy='<p style="padding: 5px;"></p>';}
this.copy=str_replace('+','#105;',this.copy);this.submitUrl="/plugins/news/extras/news_ajax.php";var postData='siteid='+this.siteId+'&pageid='+this.pageId+'&nodeid='+this.nodeId+'&copy='+this.copy;this.copy=YAHOO.util.Connect.asyncRequest('POST',this.submitUrl,updateComplete,postData);},success:function(objResponse){YX.closeDialog();var responseDiv=document.createElement('div');var wrapper=document.getElementById('wrapper');wrapper.appendChild(responseDiv);var newHTML=objResponse.responseText;},},newsSaveContent:{newsSuccess:function(objResponse){YX.closeDialog();var oldPara=$('date_edit');if(oldPara){var oldParagraph=oldPara.firstChild;if(objResponse.responseText!==undefined){oldParagraph.innerHTML=objResponse.responseText;}}},newsFailure:function(objResponse){alert("Details Not Updated Successfully. Please Try Again");}},contentChanged:function(xsEditor){xsContent=xsEditor.value;return true;},editElement:function(e,objTag){if(objTag==null)objTag=this;if(typeof objTag.nodeName=='string'){var tagType=objTag.nodeName.toLowerCase()
switch(tagType){case"h2":YX.editHeading(objTag);break;case"h3":case"h4":case"ul":case"ol":case"li":case"p":case"span":case"strong":case"em":YX.editParagraph(objTag);break;case"div":if(objTag.firstChild.nodeName.toLowerCase()=='img'){YX.editImage(objTag);}else{YX.editParagraph(objTag);}
break;default:alert("Tag Select Failed:"+objTag.nodeName);}}else{alert("Tag node name is undefined");}},editHeading:function(objHead){var buttons='spellchecker, copy, paste,,help';var editor=YX.getEditor(objHead,buttons,'Heading');},editList:function(objList){if(objList.nodeName.toLowerCase()=="li"){objList=YD.getAncestorByClassName(objList,'client_edit');}
var buttons='strong, em, underline, hyperlink, attachment,, spellchecker, copy, paste,,help';var editor=YX.getEditor(objList,buttons,'List');},editParagraph:function(objPara){if(objPara.nodeName.toLowerCase()!='div'){itemNode=objPara;while(itemNode.parentNode.nodeName.toLowerCase()!='div'){itemNode=itemNode.parentNode;}
objPara=itemNode;}
if(objPara.id=='date_edit'){var buttons='strong, em, underline, sup, sub,, hyperlink, attachment, unordered-list, ordered-list, draw-data-table,, spellchecker, copy, paste,,help';var editor=YX.getNewsEditor(objPara,buttons,'Text');}else if(objPara.id=='news_desc'){var buttons='strong, em, underline, sup, sub,, spellchecker, copy, paste,,help';var editor=YX.getEditor(objPara,buttons,'Text');}else{var buttons='strong, em, underline, sub, sup,, hyperlink, attachment';var editor=YX.getEditor(objPara,buttons,'Text');}}};if(!YX)var YX=YAHOO.news.xsEdit;YE.onDOMReady(YX.setup,YX,true);updateComplete={success:YX.saveContent.success,failure:YX.saveContent.failure,scope:YX.saveContent};newsUpdateComplete={success:YX.newsSaveContent.newsSuccess,failure:YX.newsSaveContent.newsFailure,scope:YX.newsSaveContent};function changeDesc(e,newsId){var formData=YAHOO.util.Connect.setForm("news_plugin");var siteId=$("siteid_news_plugin").value;var pageId=newsId;var newsSubmitUrl="/plugins/news/extras/news_ajax.php";var newsPostData='artPageId='+pageId+'&updatedesc=1';var newscopy=YAHOO.util.Connect.asyncRequest('POST',newsSubmitUrl,newsUpdateComplete,newsPostData);var changePara=$(pageId);changePara=changePara.getElementsByTagName('div')[0];if(Dom.hasClass(changePara,'news_desc')){changePara.innerHTML=xsEditor.value;}}
xsButtonClicked=function(id,button,state){$(id).EscapeUnicode=true;var xsEditor=document.getElementById(id);switch(button){case'save':var xsParameters=xsEditor.getElementsByTagName('param');for(var i=0;i<xsParameters.length;i++){if(xsParameters[i].getAttribute('name')=='Victim'){var oldNodeId=xsParameters[i].getAttribute('value');}
if(xsParameters[i].getAttribute('name')=='Value'){var startText=xsParameters[i].getAttribute('value');}}
YX.saveContent.nodeId=oldNodeId;var victimType=oldNodeId.substring(0,oldNodeId.indexOf('_'));var victim=document.getElementById(oldNodeId);if(xsEditor.value!==''){switch(victimType){case'header':if(navigator.appVersion.indexOf("MSIE")!==-1){var contentStuff=strstr(xsEditor.value,'h2',true);if(contentStuff){victim.innerHTML=xsEditor.value;YX.saveContent.copy=xsEditor.value;}else{var pThere=strstr(xsEditor.value,'<p>',true);var h3There=strstr(xsEditor.value,'<h3>',true);var h4There=strstr(xsEditor.value,'<h4>',true);if(pThere==''||h3There==''||h4There==''){newValue=xsEditor.value;newValue=str_replace('<p>','',newValue);newValue=str_replace('</p>','',newValue);newValue=str_replace('<h3>','',newValue);newValue=str_replace('</h3>','',newValue);newValue=str_replace('<h4>','',newValue);newValue=str_replace('</h4>','',newValue);}
victim.innerHTML=newValue;YX.saveContent.copy='<h2>'+newValue+'</h2>';}}else{var domHeader=YX.getXmlFromString(xsEditor.value);if(domHeader){domHeader=document.importNode(domHeader,true);domHeader=document.body.appendChild(domHeader);var headerTag=domHeader.getElementsByTagName('h2')[0];if(headerTag)victim.textContent=headerTag.textContent;}
domHeader.parentNode.removeChild(domHeader);YX.saveContent.copy=xsEditor.value;}
break;case'text':victim.innerHTML=xsEditor.value;YX.saveContent.copy=xsEditor.value;break;default:;}}else{var youSure=confirm("Warning: removing all content will remove this section from the page completely and cannot be recovered");if(youSure){switch(victimType){case'header':victim.innerHTML='<h2>This Is Major Heading 1</h2>';YX.saveContent.copy='<h2>This Is Major Heading 1</h2>';break;case'text':victim.innerHTML='<p style="padding: 5px;"></p>';YX.saveContent.copy='<p style="padding: 5px;"></p>';break;default:break;}}else{xsEditor.value=startText;return false;}}
YX.saveContent.update();break;case'image':break;}
return true;};xsTagListChanged=function(id){xsEditor=document.getElementById(id);var update=YX.contentChanged(xsEditor);if(!update)alert('Could not change content');return true;}
xsContentChanged=function(id){xsEditor=document.getElementById(id);var update=YX.contentChanged(xsEditor);if(!update)alert('Could not change content');return true;}
function saveButtonClicked(){xsButtonClicked('xsedit','save',null);}
function strip_tags(str,allowed_tags){var key='',tag='';var matches=allowed_array=[];var allowed_keys={};if(allowed_tags){allowed_tags=allowed_tags.replace(/[\<\> ]+/g,'');;allowed_array=allowed_tags.split(',');for(key in allowed_array){tag=allowed_array[key];allowed_keys['<'+tag+'>']=true;allowed_keys['<'+tag+' />']=true;allowed_keys['</'+tag+'>']=true;}}
matches=str.match(/(<\/?[^>]+>)/gi);for(key in matches){if(isNaN(key)){tag=matches[key].toString();if(!allowed_keys[tag]){str=str.replace(tag,"");}}}
return str;}